# Generated by Django 3.2.10 on 2021-12-11 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assesmentcategories',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AssesmentCategories',
            },
        ),
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('evaluation_id', models.AutoField(primary_key=True, serialize=False)),
                ('evaluated', models.BooleanField()),
                ('academic_year', models.DateTimeField()),
                ('created_by', models.TextField()),
                ('status', models.TextField()),
                ('max_score', models.IntegerField()),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Evaluations',
            },
        ),
        migrations.CreateModel(
            name='Subcategories',
            fields=[
                ('sub_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_cat', models.TextField()),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.assesmentcategories')),
            ],
            options={
                'db_table': 'SubCategories',
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('school_id', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.TextField()),
                ('evaluated', models.BooleanField(blank=True, null=True)),
                ('academic_year', models.DateTimeField()),
                ('school_manager', models.ForeignKey(db_column='school_manager', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Schools',
            },
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('recommender_id', models.AutoField(primary_key=True, serialize=False)),
                ('recommendation', models.TextField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.evaluations')),
            ],
            options={
                'db_table': 'Recommendations',
            },
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal', models.TextField()),
                ('goal_result', models.TextField()),
                ('max_score', models.IntegerField()),
                ('score', models.IntegerField()),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.evaluations')),
            ],
            options={
                'db_table': 'Goals',
            },
        ),
        migrations.AddField(
            model_name='evaluations',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.schools'),
        ),
        migrations.AddField(
            model_name='evaluations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Assesment',
            fields=[
                ('assesment_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator', models.TextField(blank=True, null=True)),
                ('first_evaluation', models.TextField(blank=True, null=True)),
                ('final_evaluation', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.assesmentcategories')),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.evaluations')),
            ],
            options={
                'db_table': 'Assesment',
            },
        ),
    ]
