# Generated by Django 3.2.10 on 2021-12-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluations',
            name='academic_year',
            field=models.CharField(max_length=4, verbose_name='ac year'),
        ),
        migrations.AlterField(
            model_name='schools',
            name='academic_year',
            field=models.CharField(max_length=4, verbose_name='ac year'),
        ),
    ]
