# Generated by Django 3.2.10 on 2021-12-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211211_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schools',
            name='academic_year',
            field=models.CharField(max_length=4, verbose_name='academic year'),
        ),
    ]
