# Generated by Django 3.2.9 on 2021-12-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_schools_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluations',
            name='academic_year',
            field=models.CharField(max_length=4, verbose_name='academic year'),
        ),
        migrations.AlterField(
            model_name='goals',
            name='goal_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='max_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goals',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
