# Generated by Django 3.2.9 on 2021-12-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211212_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluations',
            name='academic_year',
            field=models.CharField(max_length=4, verbose_name='Academic Year'),
        ),
        migrations.AlterField(
            model_name='evaluations',
            name='created_by',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluations',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evaluations',
            name='max_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluations',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
